.TH "ISO Master" "1" "0.7" "Andrew Smith" ""
.SH "SYNTAX"
.LP 
isomaster [\fIimage.iso\fP]
.SH "DESCRIPTION"
.LP 
ISO Master is a graphical application for working with ISO images. It can add and extract files and directories, no emulation (e.g. isolinux) and floppy emulation (e.g. DOS) El Torito boot records. Most of RockRidge and Joliet is supported.
.LP 
ISO Master can open .iso and .nrg files but can only save as ISO.
.SH "OPTIONS"
.LP 
The only command\-line parameter supported is the name of the image to open.
.SH "AUTHORS"
.LP 
Andrew Smith, <
http://littlesvr.ca/misc/contactandrew.php >
.LP 
All other contributors are listed in the CREDITS.TXT file.
